### ISSUE TITLE
Error when running yarn precontainerize

### ISSUE THREAD

**Issue by DillFrescott** [with-labs/popspace#15]
root@ad448bdddcce:/popspace# yarn precontainerize
yarn run v1.22.19
$ yarn build-lib && yarn build
$ concurrently npm:build-lib:*
[build-lib:*files]
[build-lib:*files] > build-lib:files
[build-lib:*files] > yarn workspace @withso/file-upload build
[build-lib:*files]
[build-lib:*unicorn:component]
[build-lib:*unicorn:component] > build-lib:unicorn:component
[build-lib:*unicorn:component] > yarn workspace @withso/unicorn build
[build-lib:*unicorn:component]
[build-lib:*shared]
[build-lib:*shared] > build-lib:shared
[build-lib:*shared] > yarn workspace @withso/noodle-shared build
[build-lib:*shared]
warning package.json: License should be a valid SPDX license expression
$ tsc
$ rm -rf dist && mkdir dist &&  babel src -d dist --copy-files
$ tsc
[build-lib:*unicorn:component] Error: Couldn't find preset "@babel/preset-env" relative to directory "/popspace/unicorn/component"
[build-lib:*unicorn:component]     at /usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
[build-lib:*unicorn:component]     at Array.map (<anonymous>)
[build-lib:*unicorn:component]     at OptionManager.resolvePresets (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
[build-lib:*unicorn:component]     at OptionManager.mergePresets (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
[build-lib:*unicorn:component]     at OptionManager.mergeOptions (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
[build-lib:*unicorn:component]     at OptionManager.init (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
[build-lib:*unicorn:component]     at File.initOptions (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:212:65)
[build-lib:*unicorn:component]     at new File (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:135:24)
[build-lib:*unicorn:component]     at Pipeline.transform (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
[build-lib:*unicorn:component]     at transform (/usr/lib/node_modules/babel-cli/lib/babel/util.js:50:22)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
[build-lib:*unicorn:component] Exit code: 1
[build-lib:*unicorn:component] Command: /usr/bin/node
[build-lib:*unicorn:component] Arguments: /usr/lib/node_modules/yarn/lib/cli.js build
[build-lib:*unicorn:component] Directory: /popspace/unicorn/component
[build-lib:*unicorn:component] Output:
[build-lib:*unicorn:component]
info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
[build-lib:*unicorn:component] npm run build-lib:unicorn:component exited with code 1
[build-lib:*files] error TS2468: Cannot find global value 'Promise'.
[build-lib:*files] src/FileManager.test.ts(3,1): error TS2304: Cannot find name 'jest'.
[build-lib:*files] src/FileManager.test.ts(4,1): error TS2304: Cannot find name 'jest'.
[build-lib:*files] src/FileManager.test.ts(7,21): error TS2304: Cannot find name 'jest'.
[build-lib:*files] src/FileManager.test.ts(8,5): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*files] src/FileManager.test.ts(12,15): error TS2304: Cannot find name 'jest'.
[build-lib:*files] src/FileManager.test.ts(16,23): error TS2304: Cannot find name 'jest'.
[build-lib:*files] src/FileManager.test.ts(17,23): error TS2304: Cannot find name 'jest'.
[build-lib:*files] src/FileManager.test.ts(18,20): error TS2304: Cannot find name 'jest'.
[build-lib:*files] src/FileManager.test.ts(28,18): error TS2580: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
[build-lib:*files] src/FileManager.test.ts(30,1): error TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
[build-lib:*files] src/FileManager.test.ts(33,3): error TS2304: Cannot find name 'beforeEach'.
[build-lib:*files] src/FileManager.test.ts(41,3): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
[build-lib:*files] src/FileManager.test.ts(41,36): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.
[build-lib:*files] src/FileManager.test.ts(49,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(50,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(52,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(57,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(64,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(65,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(66,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(67,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(70,3): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
[build-lib:*files] src/FileManager.test.ts(70,75): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.
[build-lib:*files] src/FileManager.test.ts(84,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(85,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(87,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(92,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(99,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(100,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(101,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(102,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(105,3): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
[build-lib:*files] src/FileManager.test.ts(105,49): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.
[build-lib:*files] src/FileManager.test.ts(113,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(114,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(116,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(121,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(127,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(138,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(139,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(140,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(141,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(142,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(148,3): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
[build-lib:*files] src/FileManager.test.ts(148,47): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.
[build-lib:*files] src/FileManager.test.ts(151,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(152,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(154,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(155,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(159,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(160,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(165,3): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
[build-lib:*files] src/FileManager.test.ts(165,73): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.
[build-lib:*files] src/FileManager.test.ts(180,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(181,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(183,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(184,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(187,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(191,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.test.ts(192,5): error TS2304: Cannot find name 'expect'.
[build-lib:*files] src/FileManager.ts(1,25): error TS2307: Cannot find module 'path' or its corresponding type declarations.
[build-lib:*files] src/FileManager.ts(2,28): error TS2307: Cannot find module 'uuid' or its corresponding type declarations.
[build-lib:*files] src/FileManager.ts(69,11): error TS2580: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
[build-lib:*files] src/FileManager.ts(69,11): error TS4033: Property 'buffer' of exported interface has or is using private name 'Buffer'.
[build-lib:*files] src/FileManager.ts(115,23): error TS2550: Property 'startsWith' does not exist on type 'string'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2015' or later.
[build-lib:*files] src/FileManager.ts(142,12): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.
[build-lib:*files] src/S3.ts(1,17): error TS2307: Cannot find module 'aws-sdk' or its corresponding type declarations.
[build-lib:*files] src/S3.ts(3,23): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
[build-lib:*files] src/S3.ts(28,45): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
[build-lib:*files] src/S3.ts(30,38): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
[build-lib:*files] src/S3.ts(31,35): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
[build-lib:*files] src/S3.ts(35,21): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.
[build-lib:*files] src/S3.ts(76,42): error TS2580: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
[build-lib:*files] src/__mocks__/imageProcessing.ts(1,34): error TS2304: Cannot find name 'jest'.
[build-lib:*files] src/__mocks__/imageProcessing.ts(1,51): error TS2580: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
[build-lib:*files] src/__mocks__/imageProcessing.ts(2,3): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*files] src/__mocks__/imageProcessing.ts(4,37): error TS2304: Cannot find name 'jest'.
[build-lib:*files] src/imageProcessing.ts(1,19): error TS2307: Cannot find module 'sharp' or its corresponding type declarations.
[build-lib:*files] src/imageProcessing.ts(5,41): error TS2580: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
[build-lib:*files] src/imageProcessing.ts(18,50): error TS2580: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
[build-lib:*files] types/withso__with-shared/index.d.ts(2,28): error TS2307: Cannot find module 'massive' or its corresponding type declarations.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
[build-lib:*files] Exit code: 1
[build-lib:*files] Command: /usr/bin/node
[build-lib:*files] Arguments: /usr/lib/node_modules/yarn/lib/cli.js build
[build-lib:*files] Directory: /popspace/file-upload
[build-lib:*files] Output:
[build-lib:*files]
info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
[build-lib:*files] npm run build-lib:files exited with code 1
[build-lib:*shared] error TS2468: Cannot find global value 'Promise'.
[build-lib:*shared] src/api/middleware.ts(1,38): error TS2307: Cannot find module '@prisma/client' or its corresponding type declarations.
[build-lib:*shared] src/api/middleware.ts(2,49): error TS2307: Cannot find module 'express' or its corresponding type declarations.
[build-lib:*shared] src/api/middleware.ts(10,3): error TS2580: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
[build-lib:*shared] src/api/middleware.ts(13,16): error TS2664: Invalid module name in augmentation, module 'express' cannot be found.
[build-lib:*shared] src/api/middleware.ts(53,10): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.
[build-lib:*shared] src/db/accounts.ts(1,25): error TS2307: Cannot find module 'express' or its corresponding type declarations.
[build-lib:*shared] src/db/config.ts(2,21): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
[build-lib:*shared] src/db/constants.ts(1,31): error TS2583: Cannot find name 'BigInt'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2020' or later.
[build-lib:*shared] src/db/events.ts(1,25): error TS2307: Cannot find module 'express' or its corresponding type declarations.
[build-lib:*shared] src/db/events.ts(2,29): error TS2307: Cannot find module 'ua-parser-js' or its corresponding type declarations.
[build-lib:*shared] src/db/events.ts(3,17): error TS2307: Cannot find module 'url' or its corresponding type declarations.
[build-lib:*shared] src/db/events.ts(8,16): error TS2664: Invalid module name in augmentation, module 'express' cannot be found.
[build-lib:*shared] src/db/magic.ts(1,27): error TS2307: Cannot find module '@prisma/client' or its corresponding type declarations.
[build-lib:*shared] src/db/pg.ts(1,23): error TS2307: Cannot find module 'async-lock' or its corresponding type declarations.
[build-lib:*shared] src/db/pg.ts(2,21): error TS2307: Cannot find module 'massive' or its corresponding type declarations.
[build-lib:*shared] src/db/pg.ts(3,16): error TS2307: Cannot find module 'pg' or its corresponding type declarations.
[build-lib:*shared] src/db/pg.ts(4,21): error TS2307: Cannot find module 'pg-monitor' or its corresponding type declarations.
[build-lib:*shared] src/db/pg.ts(33,3): error TS2304: Cannot find name 'global'.
[build-lib:*shared] src/db/pg.ts(36,12): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
[build-lib:*shared] src/db/pg.ts(39,7): error TS2304: Cannot find name 'global'.
[build-lib:*shared] src/db/pg.ts(41,4): error TS2304: Cannot find name 'global'.
[build-lib:*shared] src/db/pg.ts(106,9): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.
[build-lib:*shared] src/db/prisma.ts(1,30): error TS2307: Cannot find module '@prisma/client' or its corresponding type declarations.
[build-lib:*shared] src/db/redis/redis_base.ts(1,19): error TS2307: Cannot find module 'redis' or its corresponding type declarations.
[build-lib:*shared] src/db/redis/redis_base.ts(38,16): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/db/redis/redis_base.ts(49,16): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/db/redis/redis_base.ts(68,16): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/db/redis/redis_base.ts(103,16): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/db/redis/redis_base.ts(104,34): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.
[build-lib:*shared] src/db/redis/redis_base.ts(140,16): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/db/redis/redis_base.ts(152,16): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/db/redis/redis_base.ts(161,16): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/db/redis/redis_base.ts(167,16): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/db/redis/redis_base.ts(180,16): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/db/redis/redis_base.ts(186,16): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/db/redis/redis_base.ts(192,16): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/db/redis/redis_base.ts(198,16): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/db/redis/redis_base.ts(207,16): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/db/redis/redis_base.ts(213,16): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/db/redis/redis_base.ts(219,16): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/db/redis/redis_base.ts(225,16): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/db/redis/redis_base.ts(231,16): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/db/redis/redis_base.ts(237,16): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/db/redis/redis_base.ts(243,16): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/db/redis/redis_base.ts(249,16): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/db/redis/redis_base.ts(255,16): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/db/redis/redis_base.ts(261,16): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/db/room/data.ts(39,17): error TS2550: Property 'assign' does not exist on type 'ObjectConstructor'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2015' or later.
[build-lib:*shared] src/db/room/data.ts(74,20): error TS2583: Cannot find name 'BigInt'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2020' or later.
[build-lib:*shared] src/db/room/memberships.ts(1,22): error TS2307: Cannot find module '@prisma/client' or its corresponding type declarations.
[build-lib:*shared] src/db/room/names_and_routes.ts(1,32): error TS2307: Cannot find module 'crypto-random-string' or its corresponding type declarations.
[build-lib:*shared] src/db/room/permissions.ts(1,22): error TS2307: Cannot find module '@prisma/client' or its corresponding type declarations.
[build-lib:*shared] src/db/room/templates.ts(1,23): error TS2307: Cannot find module '@prisma/client' or its corresponding type declarations.
[build-lib:*shared] src/db/room/templates.ts(86,22): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/db/serialization.ts(8,55): error TS2583: Cannot find name 'BigInt'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2020' or later.
[build-lib:*shared] src/db/serialization.ts(30,34): error TS2583: Cannot find name 'BigInt'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2020' or later.
[build-lib:*shared] src/db/serialization.ts(40,22): error TS2583: Cannot find name 'BigInt'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2020' or later.
[build-lib:*shared] src/db/serialization.ts(48,12): error TS2583: Cannot find name 'BigInt'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2020' or later.
[build-lib:*shared] src/db/serialization.ts(55,2): error TS2583: Cannot find name 'BigInt'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2020' or later.
[build-lib:*shared] src/db/time.ts(1,20): error TS2307: Cannot find module 'moment' or its corresponding type declarations.
[build-lib:*shared] src/index.ts(15,9): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.
[build-lib:*shared] src/index.ts(18,12): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.
[build-lib:*shared] src/index.ts(26,15): error TS2307: Cannot find module '@prisma/client' or its corresponding type declarations.
[build-lib:*shared] src/lib/auth.ts(1,25): error TS2307: Cannot find module '@prisma/client' or its corresponding type declarations.
[build-lib:*shared] src/lib/auth.ts(2,20): error TS2307: Cannot find module 'moment' or its corresponding type declarations.
[build-lib:*shared] src/lib/auth.ts(72,31): error TS2583: Cannot find name 'BigInt'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2020' or later.
[build-lib:*shared] src/lib/otp.ts(1,27): error TS2307: Cannot find module '@prisma/client' or its corresponding type declarations.
[build-lib:*shared] src/lib/otp.ts(2,32): error TS2307: Cannot find module 'crypto-random-string' or its corresponding type declarations.
[build-lib:*shared] src/lib/otp.ts(3,20): error TS2307: Cannot find module 'moment' or its corresponding type declarations.
[build-lib:*shared] src/lib/routes.ts(1,27): error TS2307: Cannot find module '@prisma/client' or its corresponding type declarations.
[build-lib:*shared] src/models/actor.ts(1,34): error TS2307: Cannot find module '@prisma/client' or its corresponding type declarations.
[build-lib:*shared] src/models/profile.ts(1,23): error TS2307: Cannot find module '@prisma/client' or its corresponding type declarations.
[build-lib:*shared] src/models/profile.ts(23,16): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/models/profile.ts(26,17): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/models/room_data.ts(1,22): error TS2307: Cannot find module '@prisma/client' or its corresponding type declarations.
[build-lib:*shared] src/models/room_data.ts(52,16): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/models/room_widget.ts(1,61): error TS2307: Cannot find module '@prisma/client' or its corresponding type declarations.
[build-lib:*shared] src/models/room_with_state.ts(1,22): error TS2307: Cannot find module '@prisma/client' or its corresponding type declarations.
[build-lib:*shared] src/models/room_with_state.ts(28,22): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/models/room_with_state.ts(31,21): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/models/room_with_state.ts(50,32): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.
[build-lib:*shared] src/models/room_with_state.ts(55,11): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
[build-lib:*shared] src/net/_net.ts(2,15): error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
[build-lib:*shared] src/net/http_client.ts(1,24): error TS2307: Cannot find module 'https' or its corresponding type declarations.
[build-lib:*shared] src/net/http_client.ts(29,19): error TS2580: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
[build-lib:*shared] src/net/http_client.ts(43,16): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
[build-lib:*shared] Exit code: 2
[build-lib:*shared] Command: /usr/bin/node
[build-lib:*shared] Arguments: /usr/lib/node_modules/yarn/lib/cli.js build
[build-lib:*shared] Directory: /popspace/noodle-shared
[build-lib:*shared] Output:
[build-lib:*shared]
info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
[build-lib:*shared] npm run build-lib:shared exited with code 2
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@ad448bdddcce:/popspace#

**Comment by DillFrescott** [comment]
Im so confused. Nodejs NEVER works for me with anything

**Comment by a-type** [comment]
It looks like you haven't installed dependencies yet. Try running `yarn install` first, then run `yarn precontainerize` again.

Sorry I forgot to add that to the docs! Having worked with Node for so long, it's easy to forget things which have become automatic 😅

**Comment by DillFrescott** [comment]
Ohhhh its okay! Thank you for the response!
