### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by DillFrescott** [with-labs/popspace#16]
Ok so I got (nearly) everything working including voice and video. But then all of a sudden I went into a room and its doing this:

https://i.imgur.com/UhBzaIN.png

What does it mean? I tried restarting the machine and everything

**Comment by a-type** [comment]
Do you have a [LiveKit](https://livekit.io/) media server running, and have you set the following environment variables?

```
REACT_APP_LIVEKIT_ENDPOINT=https://your-livekit-instance.com/
LIVEKIT_API_KEY=<your livekit server key>
LIVEKIT_SECRET_KEY=<your livekit server secret key>
```

See their [getting started](https://docs.livekit.io/guides/getting-started/) guide if not. Unfortunately it's necessary to run this server separately from PopSpace right now. We would like to combine all these dependencies into one, see https://github.com/with-labs/popspace/issues/13

**Comment by DillFrescott** [comment]
Yes I had one running via a docker container

**Comment by a-type** [comment]
The error definitely indicates there's something wrong with either the networking to that container (check with their [example app](https://docs.livekit.io/guides/getting-started/#test-with-example-app) that it can reach your server) or the environment variables. The client is not able to connect to LiveKit.

For local docker I think `REACT_APP_LIVEKIT_ENDPOINT` should be `http://localhost:7880`.

**Comment by DillFrescott** [comment]
Okay. That's actually good to know because at least I know what's causing it and now I can work on fixing it!

Thank you!

**Comment by DillFrescott** [comment]
Closing for now. Ill let you know if I encounter anything else!
